ABREVIACIONES = {
    "adv. m": "Adverbio Masculino",
    "adv. m. interrog": "Adverbio Masculino Interrogativo",
    "contr": "Contracción de la preposición + artículo",
    "pron": "Pronombre",
    "conj": "Conjunción",
    "adj": "Adjetivo",
    "adj. col": "Adjetivo (Uso Coloquial)",
    "adj. y s": "Adjetivo Singular",
    "adj. y com. med": "Adjetivo (Uso Enfermedad)",
    "art. det": "Determinante Articulo",
    "art. det. f": "Determinante Atículo Femenino",
    "interj": "Interjección",
    "m": "Sustantivo Masculino",
    "m. mús": "Sustantivo Masculino (Uso Música)",
    "f": "Sustantivo Femenino",
    "v": "Verbo",
    "v. cop": "Verbo Copulativo",
    "p. p. irreg": "Verbo del Participio del Presente Irregular",
    "tr": "Verbo Transitivo",
    "tr. y prnl": "Verbo Transitivo y Verbo Pronominal ",
    "tr. der": "Verbo Transitivo (Uso Derecho)",
    "tr. mat": "Verbo Transitivo uso Matematicas",
    "tr. e intr": "Verbo Transitivo e Verbo Intrasitivo",
    "intr. y tr": "Verbo Intrasitivo e Verbo Transitivo",
    "intr.,tr. y prnl": "Verbo Transitivo e Verbo Intrasitivo e Verbo Pronominal",
    "intr": "Verbo Intrasitivo",
    "cop": "Verbo Copulativo",
    "intr. col": "Verbo Intransitivo (Uso Coloquial)",
    "suf": "Sufijo",
    "pref": "Prefijo"
}
